---
dwh:
  database: picnic_fr_prod
  warehouse: ANALYSIS
  role: analyst
  account: uj82639.eu-west-1
  username: !ENV_DWH_USERNAME
picnic-client:
  keycloak: null
datalayer:
  url: "https://datalayer-dev.fr.picnicinternational.com"
